<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1', '/dededln/uploads/allimg/170713/1-1FG3110253954.png');
$maNum = 1;
$myaddons[$maNum] = array('2', '/dededln/uploads/allimg/170713/1-1FG3110315B7.png');
$maNum = 2;
$myaddons[$maNum] = array('3', '/dededln/uploads/allimg/170713/1-1FG311032B13.png');
$maNum = 3;
$myaddons[$maNum] = array('4', '/dededln/uploads/allimg/170713/1-1FG311060RR.png');
$maNum = 4;
$myaddons[$maNum] = array('5', '/dededln/uploads/allimg/170713/1-1FG3110624926.png');
$maNum = 5;
$myaddons[$maNum] = array('6', '/dededln/uploads/allimg/170713/1-1FG311063MF.png');
$maNum = 6;
$myaddons[$maNum] = array('7', '/dededln/uploads/allimg/170713/1-1FG311064U61.png');
$maNum = 7;
